### ISSUE TITLE
How to use this API in the ethereum

### ISSUE THREAD

**Issue by CokeBear666** [NovaCrypto/BIP44#5]
How to use this API in the ethereum?   I have no idea

**Comment by CokeBear666** [comment]
I try to add a type like 
https://github.com/satoshilabs/slips/blob/master/slip-0044.md
but I am fail

**Comment by westonal** [comment]
It's not really clear what you want to do? Please add more detail.

**Comment by CokeBear666** [comment]
I want to use BIP39 and BIP44 api to create an ethereum  address.
How can I do?
`PrivateKey rootKey = PrivateKey.fromSeed(new SeedCalculator().calculateSeed(sb.toString(),""), Bitcoin.MAIN_NET);`
It  can only create BTC rootKey.

**Comment by westonal** [comment]
Ethereum addresses are their own beast and not covered by these BIPs.

Closest I can get you is the private key:

```
byte[] privateKey = Arrays.copyOfRange(
                ExtendedPrivateKey.fromSeed(new SeedCalculator().calculateSeed(sb.toString(), ""),
                        Bitcoin.MAIN_NET //only used for serialization and we are throwing it away anyway
                ).extendedKeyByteArray(), 46, 78);
```

What happens next is not clear, but here are some resources:

https://bitcoin.stackexchange.com/a/42057/3511

https://github.com/iancoleman/bip39/blob/master/src/js/index.js#L800-L810

https://github.com/iancoleman/bip39/blob/master/src/js/ethereumjs-util.js#L6542-L6549
