### ISSUE TITLE
Get an address from an Extended Public Key

### ISSUE THREAD

**Issue by trixprod** [NovaCrypto/BIP44#6]
Hello,
I have successfully derived an Extended Public Key using the BIP32 project ( version 0.0.9 ).
So i can derive each address from an Bitcoin Mainet Xpub.

I would like to do the same with an Ethereum Extended Public Key.
Unfortunatly i can't achieve that using BIP44 code.

Imo, i am missing something.
Can you provide a test or a snippet of code showing how to do that ?

Thank you.

**Comment by reliefeai** [comment]
+1

**Comment by trixprod** [comment]
Hello @TouchYou 
I created a repository with BIP32 /  BIP44 derivation addresses in NodeJS : 
https://github.com/trixprod/hdwallet-addresses

Would be nice to use NovaCrypto in Java.

**Comment by westonal** [comment]
Hi, I am not sure exactly but you can get the raw private key like so:
https://github.com/NovaCrypto/BIP44/issues/5#issuecomment-363079950
